#!/usr/bin/env bash

######## Sketchybarrc ########
##############################

# Import variables

source "$HOME/.config/sketchybar/variables.sh"

######## Sketchybar config ########
###################################

# Defaults

sketchybar --bar height=30 \
	color="$BAR_COLOR" \
	shadow="$SHADOW" \
	position=top \
	sticky=on \
	padding_right=9 \
	padding_left=9 \
	corner_radius="$CORNER_RADIUS" \
	y_offset=5 \
	margin=5 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

# Aerospace

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

######## Sketchybar items ########
##################################

# Left

source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

# Center

source "$ITEM_DIR/music.sh"

# Right

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

######## Finalizing Sketchbar ########
######################################

sketchybar --hotload true

sketchybar --update

echo "Sketchybar configuration loaded."
